 
{
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  quoted_status_id: 1330281539050102800,
  quoted_status_id_str: '1330281539050102803',
  quoted_status: {
    created_at: 'Sat Nov 21 22:46:49 +0000 2020',
    id: 1330281539050102800,
    id_str: '1330281539050102803',
    text: 'Do not forget: A Green New Deal not only helps us lead the world in combating climate change, but will create milli… https://t.co/clId12WuIQ',      
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    truncated: true,
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 29442313,
      id_str: '29442313',
      name: 'Bernie Sanders',
      screen_name: 'SenSanders',
      location: 'Vermont/DC',
      url: 'http://www.sanders.senate.gov/',
      description: 'U.S. Senator Bernie Sanders of Vermont is the longest-serving independent in congressional history.',
      translator_type: 'none',
      protected: false,
      verified: true,
      followers_count: 10854890,
      friends_count: 2334,
      listed_count: 26502,
      favourites_count: 359,
      statuses_count: 21978,
      created_at: 'Tue Apr 07 13:02:35 +0000 2009',
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      profile_background_color: '000000',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_link_color: '03102D',
      profile_sidebar_border_color: 'FFFFFF',
      profile_sidebar_fill_color: 'D6CCB6',
      profile_text_color: '304562',
      profile_use_background_image: true,
      profile_image_url: 'http://pbs.twimg.com/profile_images/794619281271033856/Fs0QQaH7_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/794619281271033856/Fs0QQaH7_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/29442313/1430854323',
      default_profile: false,
      default_profile_image: false,
      following: null,
      follow_request_sent: null,
      notifications: null
    }
  }
} 
